### ISSUE TITLE
Research taro

### ISSUE THREAD

**Issue by whoabuddy** [bitcoin-nfts/bitcoin-colors#10]
Could be interesting to explore:

https://docs.lightning.engineering/the-lightning-network/taro

**Comment by larrysalibra** [comment]
Might be worth looking at RGB as well. My understanding is that there is some degree of similarity between Taro and RGB. https://bitcoinmagazine.com/guides/a-brief-introduction-to-rgb-protocols
https://github.com/LNP-BP/LNPBPs/blob/master/lnpbp-0020.md

**Comment by donpdonp** [comment]
Here's a few attributes for comparison, suggestions welcome.

| | Bitcoin NFT | Taro | RGB contract | 
| ---| --------- | -------- | -------------- |
| NFT Platform | Stacks | Bitcoin | Bitcoin |
|Transaction starts as | BTC transaction | BTC transaction | BTC Transaction|
|Lightening transfers | No | Yes | Yes|
|Reference Implementation | bitcoin-nfts/mint-runner | lightninglabs/taro | RGB-WG/rgb-core|
|P2P Metadata | Gaia | Universe | Bifrost|

**Comment by donpdonp** [comment]
@larrysalibra thanks for the link. RGB looks really advanced, with its own VM (the AluVM) and a general contract execution mechanism that is off-chain. My sense is it will be in the R&D phase for some time, but I put it on the chart anyways.

**Comment by whoabuddy** [comment]
Closing this out as we discussed this on a few of the technical calls, and at this time it doesn't look like a path that would be helpful to what we are trying to achieve.
