### ISSUE TITLE
Research chainhooks and HTLC

### ISSUE THREAD

**Issue by whoabuddy** [bitcoin-nfts/bitcoin-colors#11]
Instead of using a dedicated authority address, can we provide the address for the HTLC script after it's created? 

(Create it on the fly)

Post as a JSON file to API for chainhooks.

**Comment by lgalabru** [comment]
https://github.com/hirosystems/clarinet/blob/develop/components/chainhook-event-observer/doc/openapi.json

**Comment by whoabuddy** [comment]
Closing in favor of #24
