### ISSUE TITLE
Move clarity contracts to own folder

### ISSUE THREAD

**Issue by friedger** [bitcoin-nfts/bitcoin-colors#39]
Currently, clarinet config is a top level file. All clarity files should be located in a folder like `backend-public`

**Comment by whoabuddy** [comment]
This repo was intended for the backend code - a separate repo will be created for the frontend per #28, and a separate repo exists for the conversion tool so it can be published as a separate package: [bitcoin-colors-generator](https://github.com/bitcoin-nfts/bitcoin-colors-generator).

With that in mind would you still move all the Clarity files / clarinet config?

**Comment by whoabuddy** [comment]
Closing this out but feel free to re-open if anyone thinks this should still be reorganized.
